#!/usr/bin/env python3
import rospy
from nav_msgs.msg import OccupancyGrid
from scipy.sparse import csr_matrix
import numpy as np
import requests
from datetime import datetime
import sys

class HeatmapSaver(object):
    def __init__(self):
        self.url = 'http://localhost:5000/insert'

        self.heatmap_subscriber = rospy.Subscriber(
            "/costmap_generator/costmap/costmap", OccupancyGrid, self.save_heatmap)

        costmap = rospy.wait_for_message("/map", OccupancyGrid, timeout=100)
        # Throw exception if no costmap created
        self.width = costmap.info.width
        self.height = costmap.info.height
        self.size = (self.height, self.width)
        self.mask = np.array(costmap.data).reshape(self.size).astype(bool)
        self.mask = (~self.mask).astype(int)
        self.mask = csr_matrix(self.mask)
        body = {
            'name': 'base_mask',
            'width': self.width,
            'height': self.height,
            'indices': self.mask.indices.tolist(),
            'indptr': self.mask.indptr.tolist(),
        }
        requests.post(self.url, json = body)
        self.mask = self.mask.toarray()

    def save_heatmap(self, msg):
        data = np.array(msg.data).reshape(self.size)
        print(f"Data shape: {data.shape}\nMask shape: {self.mask.shape}")
        try:
            masked_data = csr_matrix(data * self.mask)
            print("It worked")
        except Exception as e:
            print(e)
        body = {
            'date': datetime.now().isoformat(),
            'indices': masked_data.indices.tolist(),
            'indptr': masked_data.indptr.tolist(),
        }
        requests.post(self.url, json = body)

if __name__ == '__main__':
    rospy.init_node('heatmap_saver', anonymous=True)
    try:
        heatmap = HeatmapSaver()
        rospy.spin()
    except:
        # something

