observation_sources: scan scan_2
scan: {sensor_frame: sensor_laser, data_type: LaserScan, topic: /sensors/laser_scan, marking: true, clearing: true,
       expected_update_rate: 0.4, max_obstacle_height: 0.4, min_obstacle_height: 0.001}

scan_2: {sensor_frame: sensor_laser_2, data_type: LaserScan, topic: /sensors/laser_scan_2, marking: true, clearing: true,
       expected_update_rate: 0.4, max_obstacle_height: 0.4, min_obstacle_height: 0.001}